// node scripts/build-amll.cjs <node_modules containing @applemusic-like-lyrics/core and esbuild>
// Bundle the pinned AMLL core into one ES module; see browser/amll/README.md.
const fs = require('node:fs');
const path = require('node:path');
const modules = path.resolve(process.argv[2] || 'node_modules');
const esbuild = require(path.join(modules, 'esbuild'));
const root = path.join(__dirname, '..');
const core = path.join(modules, '@applemusic-like-lyrics/core');
const { version, license } = require(path.join(core, 'package.json'));
const expected = fs.readFileSync(path.join(root, 'browser/amll/VERSION'), 'utf8').trim();
if (version !== expected) throw new Error(`@applemusic-like-lyrics/core ${version} installed, ${expected} pinned`);
const stub = path.join(root, 'browser/amll/pixi-stub.mjs');
const banner = `// Generated by scripts/build-amll.cjs from @applemusic-like-lyrics/core ${version} (${license}).\n`
  + '// Source: https://github.com/amll-dev/applemusic-like-lyrics — see browser/amll.';
esbuild.buildSync({
  entryPoints: [path.join(root, 'browser/amll/entry.mjs')],
  outfile: path.join(root, 'src/ui/lyrics/amll-core.mjs'),
  bundle: true, format: 'esm', target: 'es2022', minify: true, legalComments: 'inline',
  nodePaths: [modules], banner: { js: banner },
  alias: Object.fromEntries(['app', 'core', 'display', 'filter-blur', 'filter-bulge-pinch', 'filter-color-matrix', 'sprite']
    .map(name => [`@pixi/${name}`, stub])),
});
// Hovering the player un-blurs all lines; on touch screens :hover sticks after a tap, so keep it to real hover
const hoverUnblur = '  &:hover .FmKaba_lyricLine, &:hover .FmKaba_lyricLineWrapper {\n    filter: unset !important;\n  }\n';
const style = fs.readFileSync(path.join(core, 'dist/style.css'), 'utf8');
if (!style.includes(hoverUnblur)) throw new Error('AMLL hover un-blur rule not found in dist/style.css');
fs.writeFileSync(path.join(root, 'src/ui/lyrics/amll.css'),
  `/* Generated by scripts/build-amll.cjs from @applemusic-like-lyrics/core ${version} (${license}). */\n`
  + style.replace(hoverUnblur, '  @media (hover: hover) {\n'
    + '    &:hover .FmKaba_lyricLine, &:hover .FmKaba_lyricLineWrapper {\n      filter: unset !important;\n    }\n  }\n'));
